import type { HostCommandHandlers } from "./host-command-router";
import type { TaskService } from "./task-service";

export const createTaskCommandHandlers = (taskService: TaskService): HostCommandHandlers => ({
  agent_session_upsert: (args) => taskService.agentSessionUpsert(args),
  agent_sessions_list_bulk: (args) => taskService.agentSessionsListBulk(args),
  build_blocked: (args) => taskService.buildBlocked(args),
  build_completed: (args) => taskService.buildCompleted(args),
  build_resumed: (args) => taskService.buildResumed(args),
  build_start: (args) => taskService.buildStart(args),
  human_approve: (args) => taskService.humanApprove(args),
  human_request_changes: (args) => taskService.humanRequestChanges(args),
  qa_approved: (args) => taskService.qaApproved(args),
  qa_rejected: (args) => taskService.qaRejected(args),
  repo_pull_request_sync: (args) => taskService.repoPullRequestSync(args),
  task_approval_context_get: (args) => taskService.getApprovalContext(args),
  task_pull_request_detect: (args) => taskService.detectPullRequest(args),
  task_direct_merge: (args) => taskService.directMerge(args),
  task_direct_merge_complete: (args) => taskService.completeDirectMerge(args),
  task_pull_request_link_merged: (args) => taskService.linkMergedPullRequest(args),
  task_pull_request_unlink: (args) => taskService.unlinkPullRequest(args),
  task_pull_request_upsert: (args) => taskService.upsertPullRequest(args),
  task_create: (args) => taskService.createTask(args),
  task_delete: (args) => taskService.deleteTask(args),
  task_defer: (args) => taskService.deferTask(args),
  task_metadata_get: (args) => taskService.getTaskMetadata(args),
  task_resume_deferred: (args) => taskService.resumeDeferredTask(args),
  task_reset: (args) => taskService.resetTask(args),
  task_reset_implementation: (args) => taskService.resetImplementation(args),
  task_transition: (args) => taskService.transitionTask(args),
  task_update: (args) => taskService.updateTask(args),
  set_plan: (args) => taskService.setPlan(args),
  set_spec: (args) => taskService.setSpec(args),
  plan_save_document: (args) => taskService.savePlanDocument(args),
  spec_save_document: (args) => taskService.saveSpecDocument(args),
  tasks_list: (args) => taskService.listTasks(args),
});
