changelog:
  categories:
    - title: 🚀 Features
      labels:
        - enhancement
    - title: 🐛 Fixes
      labels:
        - bug
    - title: 🏗️ Refactoring
      labels:
        - refactoring
    - title: 📝 Documentation
      labels:
        - documentation
  exclude:
    labels:
      - duplicate
      - invalid
      - question
      - wontfix
