export const KANBAN_LANE_WIDTH_PX = 328;
export const KANBAN_LANE_WIDTH_CLASS = "w-[328px] min-w-[328px]";

const KANBAN_LANE_HORIZONTAL_PADDING_PX = 12;
const KANBAN_CARD_HORIZONTAL_PADDING_PX = 14;
const KANBAN_CARD_BORDER_PX = 1;

export const KANBAN_CARD_CONTENT_WIDTH_PX =
  KANBAN_LANE_WIDTH_PX -
  KANBAN_LANE_HORIZONTAL_PADDING_PX * 2 -
  KANBAN_CARD_HORIZONTAL_PADDING_PX * 2 -
  KANBAN_CARD_BORDER_PX * 2;

export const KANBAN_LABEL_ROW_GAP_PX = 6;
