// Shared inputs exercise both the pure resolver and Markdown's destination encoding.
export const chatFileLinkSuffixes = ["", ":42", ":42:7", "#L42", "#L42-L50"] as const;

export const validChatFileDestinations = [
  ["src/app.ts", "/repo/task", "src/app.ts"],
  ["./src/app.ts", "/repo/task", "src/app.ts"],
  ["/repo/task/src/app.ts", "/repo/task", "src/app.ts"],
  ["file:///repo/task/src/app.ts", "/repo/task", "src/app.ts"],
  ["a%20b.ts", "/repo/task", "a b.ts"],
  ["%E6%96%87.ts", "/repo/task", "文.ts"],
  ["a%3A42", "/repo/task", "a:42"],
  ["a%23L42", "/repo/task", "a#L42"],
  ["a%2520b", "/repo/task", "a%20b"],
  ["src/../a", "/repo/task", "a"],
  ["dir/a:b.ts", "/repo/task", "dir/a:b.ts"],
  ["Makefile", "/repo/task", "Makefile"],
  ["ab", "/repo/task", "ab"],
  ["./a", "/repo/task", "a"],

  [String.raw`C:\repo\task\src\app.ts`, "C:/Repo/Task", "src/app.ts"],
  ["C:%5Crepo%5Ctask%5Csrc%5Capp.ts", "C:/Repo/Task", "src/app.ts"],
  ["c:%5crepo%5ctask%5cSrc%5cApp.ts", "C:/Repo/Task", "Src/App.ts"],
  ["C:%2Frepo%2Ftask%2Fsrc%2Fapp.ts", "C:/Repo/Task", "src/app.ts"],
  ["c:/repo/src/app.ts", "C:/repo", "src/app.ts"],
  ["file:///%43:/repo/src/app.ts", "C:/repo", "src/app.ts"],
  ["C:/repo/task/src/app.ts", "C:/Repo/Task", "src/app.ts"],
  ["file:///C:/repo/task/src/app.ts", "C:/Repo/Task", "src/app.ts"],
  ["c:/rEpO/tAsK/Src/App.ts", "C:\\Repo\\Task", "Src/App.ts"],
  ["file:///%63:/rEpO/tAsK/Src/App.ts", "C:\\Repo\\Task", "Src/App.ts"],
  ["file:///C:%2Frepo/task/src/app.ts", "C:/repo/task", "src/app.ts"],
  ["file:///C:%5Crepo%5Ctask%5Csrc%5Capp.ts", "C:/repo/task", "src/app.ts"],
  ["%43:%5Crepo%5Ctask%5Csrc%5Capp.ts", "C:/repo/task", "src/app.ts"],
  ["file:///%43:%5Crepo%5Ctask%5Csrc%5Capp.ts", "C:/repo/task", "src/app.ts"],
] as const;

export const invalidChatFileDestinations = [
  ["file:42", "/repo/task", "Use a local file URI without a remote authority."],
  ["C:42", "C:/repo/task", "Drive-relative file paths are not supported."],
  ["%43:42", "C:/repo/task", "Drive-relative file paths are not supported."],
  ["file:///C:42", "C:/repo/task", "Drive-relative file paths are not supported."],
  ["README.md:-1", "/repo/task", "The file line reference is invalid."],
  ["file:///C:%255Crepo/task/a", "C:/repo/task", "Drive-relative file paths are not supported."],
  [
    "C:%255Crepo%5Ctask%5Csrc%5Capp.ts",
    "C:/repo/task",
    "Drive-relative file paths are not supported.",
  ],
  ["README.md:42:no", "/repo/task", "The file line reference is invalid."],
  ["README.md:0", "/repo/task", "The file line reference is invalid."],
  ["a#bad", "/repo/task", "The file line reference is invalid."],
  ["a:0", "/repo/task", "Drive-relative file paths are not supported."],
  ["a:42", "/repo/task", "Drive-relative file paths are not supported."],
  ["a:42:0", "/repo/task", "Drive-relative file paths are not supported."],
  ["a#L4-L2", "/repo/task", "The file line reference is invalid."],
  ["/repo/task", "/repo/task", "The destination must name a file."],
  ["src/", "/repo/task", "The destination must name a file."],
  ["file://server/repo/task/a", "/repo/task", "Use a local file URI without a remote authority."],
  ["a?raw", "/repo/task", "File links do not support query strings."],
  ["a%00b", "/repo/task", "The file path contains control characters."],
  ["a%ZZ", "/repo/task", "The file path has invalid percent encoding."],
  ["C:/repo/a", "/repo/task", "The absolute path does not match the Build Worktree platform."],
  ["C:src/app.ts", "C:/repo/task", "Drive-relative file paths are not supported."],
] as const;
