import type { AgentChatModel } from "@/components/features/agents/agent-chat";
import type { AgentStudioHeaderModel } from "@/components/features/agents/agent-studio-header";
import type { AgentStudioTaskTabsModel } from "@/components/features/agents/agent-studio-task-tabs";
import { createChatSettingsFixture } from "@/test-utils/shared-test-fixtures";

export const createAgentChatModelFixture = (): AgentChatModel => {
  const scrollToBottomOnSendRef = { current: null };
  return {
    chatSettings: createChatSettingsFixture(),
    thread: {
      modelCatalog: null,
      transcript: {
        kind: "empty",
        target: null,
        displayedSessionKey: null,
        notice: null,
        session: null,
        shouldResetWindow: false,
      },
      runtimePresentation: {
        runtimeKind: null,
        presentToolCall: (toolName) => ({ kind: "regular", displayName: toolName }),
        supportedApprovalReplyOutcomes: null,
      },
      isSessionWorking: false,
      isInteractionEnabled: false,
      emptyState: null,
      isStarting: false,
      isSending: false,
      sessionAgentColors: {},
      pendingApprovalRequests: [],
      pendingQuestionRequests: [],
      todos: [],
      canSubmitQuestionAnswers: false,
      isSubmittingQuestionByRequestId: {},
      onSubmitQuestionAnswers: async () => {},
      canReplyToApprovals: false,
      isSubmittingApprovalByRequestId: {},
      approvalReplyErrorByRequestId: {},
      onReplyApproval: async () => {},
      sessionAuxiliaryError: null,
      todoPanelCollapsed: false,
      onToggleTodoPanel: () => {},
      messagesContainerRef: { current: null },
      scrollToBottomOnSendRef,
      syncBottomAfterComposerLayoutRef: { current: null },
    },
    composer: {
      displayedSessionKey: null,
      isInteractionEnabled: false,
      isReadOnly: true,
      readOnlyReason: "No session selected.",
      busySendBlockedReason: null,
      draftScope: { key: "task-1", persistence: null },
      onSend: async () => false,
      isSending: false,
      isStarting: false,
      isSessionWorking: false,
      isWaitingInput: false,
      isModelSelectionPending: false,
      selectedModelSelection: null,
      isSelectionCatalogLoading: false,
      supportsAttachments: false,
      supportsSlashCommands: false,
      supportsFileSearch: false,
      supportsSkillReferences: false,
      supportsSubagentReferences: false,
      slashCommandCatalog: null,
      slashCommands: [],
      slashCommandsError: null,
      isSlashCommandsLoading: false,
      skillCatalog: null,
      skills: [],
      skillsError: null,
      isSkillsLoading: false,
      subagentCatalog: null,
      subagents: [],
      subagentsError: null,
      isSubagentsLoading: false,
      searchFiles: async () => [],
      agentOptions: [],
      modelPicker: {
        runtimes: [],
        value: null,
        selectionPolicy: { kind: "editable" },
        favoriteState: {
          favorites: [],
          isLoading: false,
          readError: null,
          isMutationPending: false,
          mutationError: null,
          canMutate: true,
          toggleFavorite: () => {},
          retryRead: () => {},
          retryMutation: () => {},
        },
        onValueChange: () => {},
        onOpenChange: () => {},
      },
      variantOptions: [],
      onSelectAgent: () => {},
      onSelectVariant: () => {},
      contextUsage: null,
      canStopSession: false,
      onStopSession: () => {},
      composerFormRef: { current: null },
      composerEditorRef: { current: null },
      onComposerEditorInput: () => {},
      scrollToBottomOnSendRef,
      syncBottomAfterComposerLayoutRef: { current: null },
    },
  };
};

export const createAgentStudioTaskTabsModelFixture = (): AgentStudioTaskTabsModel => ({
  tabs: [],
  availableTabTasks: [],
  isLoadingAvailableTabTasks: false,
  onSelectTab: () => {},
  onCreateTab: () => {},
  onCloseTab: () => {},
  onReorderTab: () => {},
  agentStudioReady: true,
});

export const createAgentStudioHeaderModelFixture = (): AgentStudioHeaderModel => ({
  taskTitle: "Task 1",
  taskId: "task-1",
  onOpenTaskDetails: () => {},
  selectedRole: "planner",
  workflowSteps: [],
  onWorkflowStepSelect: () => {},
  sessionSelector: {
    value: "",
    groups: [],
    disabled: false,
    onValueChange: () => {},
    shouldAutofocusComposerForValue: () => false,
  },
  sessionCreateOptions: [],
  onPrepareMessageFirstSession: () => {},
  quickActions: [],
  primaryQuickAction: null,
  onQuickAction: () => {},
  onResolveGitConflictQuickAction: null,
  isCreatingSession: false,
  agentStudioReady: true,
});
