import {
  CLAUDE_RUNTIME_COMMAND_CONTRACTS,
  CLAUDE_RUNTIME_HOST_COMMAND_NAMES,
  acceptedAgentUserMessageSchema,
  agentSessionControlSummarySchema,
  agentSessionLiveLoadContextResultSchema,
  agentSessionLiveLoadDiffResultSchema,
  agentSessionLiveReadResultSchema,
  agentSessionLiveSnapshotSchema,
  agentSessionRecordSchema,
  appPlatformSchema,
  buildSessionBootstrapSchema,
  codexAppServerRequestResultSchema,
  commitsAheadBehindSchema,
  devServerGroupStateSchema,
  directoryListingSchema,
  fileDiffSchema,
  fileStatusSchema,
  gitBranchSchema,
  gitCommitAllResultSchema,
  gitConflictAbortResultSchema,
  gitCurrentBranchSchema,
  gitFetchRemoteResultSchema,
  gitProviderRepositorySchema,
  gitPullBranchResultSchema,
  gitPushBranchResultSchema,
  gitRebaseAbortResultSchema,
  gitRebaseBranchResultSchema,
  gitResetWorktreeSelectionResultSchema,
  gitWorktreeStatusSchema,
  gitWorktreeStatusSummarySchema,
  gitWorktreeSummarySchema,
  hostCommandAcknowledgementResponseSchema,
  hostCommandBooleanResponseSchema,
  hostCommandEmptyResponseSchema,
  hostCommandNonEmptyStringResponseSchema,
  localAttachmentPathResponseSchema,
  pullRequestReviewContextSchema,
  pullRequestSchema,
  repoConfigSchema,
  repoRuntimeHealthCheckSchema,
  runtimeCheckSchema,
  runtimeDescriptorSchema,
  runtimeExecutableCheckSchema,
  runtimeInstanceSummarySchema,
  settingsSnapshotSchema,
  systemCheckSchema,
  systemOpenInToolInfoSchema,
  taskAgentSessionsSchema,
  taskApprovalContextLoadResultSchema,
  taskAssetStageResultSchema,
  taskCardSchema,
  taskDirectMergeResultSchema,
  taskMetadataDocumentSchema,
  taskMetadataPayloadSchema,
  taskPullRequestDetectResultSchema,
  taskSessionBootstrapSchema,
  taskStoreCheckSchema,
  taskWorktreeSummarySchema,
  terminalCloseResponseSchema,
  terminalCreateResponseSchema,
  terminalListResponseSchema,
  terminalPreparePathInputResponseSchema,
  workspaceFileTreeSchema,
  workspaceRecordSchema,
  workspaceTextFileReadResultSchema,
  workspaceTextFileWriteResultSchema,
  jsonValueSchema,
  type JsonValue,
} from "@openducktor/contracts";
import { z } from "zod";
import { HostValidationError } from "../../effect/host-errors";

export const HOST_COMMAND_NAMES = [
  "agent_session_control_fork",
  "agent_session_control_release",
  "agent_session_control_resume",
  "agent_session_control_send",
  "agent_session_control_start",
  "agent_session_control_stop",
  "agent_session_control_update_model",
  "agent_session_delete",
  "agent_session_live_list",
  "agent_session_live_load_context",
  "agent_session_live_load_diff",
  "agent_session_live_read",
  "agent_session_live_refresh",
  "agent_session_live_reply_approval",
  "agent_session_live_reply_question",
  "agent_session_stop",
  "agent_session_upsert",
  "agent_sessions_list",
  "agent_sessions_list_for_tasks",
  "build_blocked",
  "build_completed",
  "build_resumed",
  "build_start",
  ...CLAUDE_RUNTIME_HOST_COMMAND_NAMES,
  "codex_app_server_request",
  "dev_server_get_state",
  "dev_server_restart",
  "dev_server_start",
  "dev_server_stop",
  "filesystem_list_directory",
  "filesystem_list_tree",
  "filesystem_read_text_file",
  "filesystem_write_text_file",
  "git_abort_conflict",
  "git_canonicalize_path",
  "git_commit_all",
  "git_commits_ahead_behind",
  "git_create_worktree",
  "git_fetch_remote",
  "git_get_branches",
  "git_get_current_branch",
  "git_get_diff",
  "git_get_status",
  "git_get_worktree_status",
  "git_get_worktree_status_summary",
  "git_pull_branch",
  "git_push_branch",
  "git_rebase_abort",
  "git_rebase_branch",
  "git_remove_worktree",
  "git_reset_worktree_selection",
  "git_switch_branch",
  "human_approve",
  "human_request_changes",
  "open_external_url",
  "plan_get",
  "plan_save_document",
  "pull_request_review_context_get",
  "qa_approved",
  "qa_get_report",
  "qa_rejected",
  "repo_pull_request_sync",
  "repo_runtime_health",
  "repo_runtime_health_status",
  "runtime_check",
  "runtime_definitions_list",
  "runtime_ensure",
  "runtime_executables_check",
  "runtime_list",
  "runtime_require",
  "runtime_stop",
  "set_plan",
  "set_spec",
  "set_theme",
  "spec_get",
  "spec_save_document",
  "system_check",
  "system_get_platform",
  "system_list_open_in_tools",
  "system_open_directory_in_tool",
  "task_approval_context_get",
  "task_asset_discard_staged",
  "task_asset_stage",
  "task_close",
  "task_create",
  "task_delete",
  "task_direct_merge",
  "task_direct_merge_complete",
  "task_metadata_get",
  "task_pull_request_detect",
  "task_pull_request_link_merged",
  "task_pull_request_unlink",
  "task_pull_request_upsert",
  "task_reset",
  "task_reset_implementation",
  "task_session_bootstrap_abort",
  "task_session_bootstrap_complete",
  "task_session_bootstrap_prepare",
  "task_session_startup_lease_abort",
  "task_session_startup_lease_complete",
  "task_session_startup_lease_prepare",
  "task_store_check",
  "task_transition",
  "task_update",
  "task_worktree_get",
  "tasks_list",
  "terminal_close",
  "terminal_create",
  "terminal_list",
  "terminal_prepare_path_input",
  "workspace_add",
  "workspace_detect_github_repository",
  "workspace_get_repo_config",
  "workspace_get_settings_snapshot",
  "workspace_list",
  "workspace_reorder",
  "workspace_resolve_local_attachment_path",
  "workspace_save_repo_settings",
  "workspace_save_settings_snapshot",
  "workspace_select",
  "workspace_stage_local_attachment",
  "workspace_update_agent_model_favorites",
  "workspace_update_global_git_config",
  "workspace_update_repo_config",
  "workspace_update_repo_hooks",
] as const;

export type HostCommandName = (typeof HOST_COMMAND_NAMES)[number];

type HostCommandResponseSchema = z.ZodType;

const asHostCommandResponseSchema = <Schema extends HostCommandResponseSchema>(
  schema: Schema,
): Schema => schema;

export const HOST_COMMAND_RESPONSE_SCHEMAS = {
  agent_session_control_fork: asHostCommandResponseSchema(agentSessionControlSummarySchema),
  agent_session_control_release: asHostCommandResponseSchema(hostCommandEmptyResponseSchema),
  agent_session_control_resume: asHostCommandResponseSchema(agentSessionControlSummarySchema),
  agent_session_control_send: asHostCommandResponseSchema(acceptedAgentUserMessageSchema),
  agent_session_control_start: asHostCommandResponseSchema(agentSessionControlSummarySchema),
  agent_session_control_stop: asHostCommandResponseSchema(hostCommandEmptyResponseSchema),
  agent_session_control_update_model: asHostCommandResponseSchema(hostCommandEmptyResponseSchema),
  agent_session_delete: asHostCommandResponseSchema(hostCommandBooleanResponseSchema),
  agent_session_live_list: asHostCommandResponseSchema(z.array(agentSessionLiveSnapshotSchema)),
  agent_session_live_load_context: asHostCommandResponseSchema(
    agentSessionLiveLoadContextResultSchema,
  ),
  agent_session_live_load_diff: asHostCommandResponseSchema(agentSessionLiveLoadDiffResultSchema),
  agent_session_live_read: asHostCommandResponseSchema(agentSessionLiveReadResultSchema),
  agent_session_live_refresh: asHostCommandResponseSchema(hostCommandEmptyResponseSchema),
  agent_session_live_reply_approval: asHostCommandResponseSchema(hostCommandEmptyResponseSchema),
  agent_session_live_reply_question: asHostCommandResponseSchema(hostCommandEmptyResponseSchema),
  agent_session_stop: asHostCommandResponseSchema(hostCommandAcknowledgementResponseSchema),
  agent_session_upsert: asHostCommandResponseSchema(hostCommandBooleanResponseSchema),
  agent_sessions_list: asHostCommandResponseSchema(z.array(agentSessionRecordSchema)),
  agent_sessions_list_for_tasks: asHostCommandResponseSchema(z.array(taskAgentSessionsSchema)),
  build_blocked: asHostCommandResponseSchema(taskCardSchema),
  build_completed: asHostCommandResponseSchema(taskCardSchema),
  build_resumed: asHostCommandResponseSchema(taskCardSchema),
  build_start: asHostCommandResponseSchema(buildSessionBootstrapSchema),
  claude_runtime_file_status: asHostCommandResponseSchema(
    CLAUDE_RUNTIME_COMMAND_CONTRACTS.fileStatus.responseSchema,
  ),
  claude_runtime_list_models: asHostCommandResponseSchema(
    CLAUDE_RUNTIME_COMMAND_CONTRACTS.listModels.responseSchema,
  ),
  claude_runtime_list_skills: asHostCommandResponseSchema(
    CLAUDE_RUNTIME_COMMAND_CONTRACTS.listSkills.responseSchema,
  ),
  claude_runtime_list_slash_commands: asHostCommandResponseSchema(
    CLAUDE_RUNTIME_COMMAND_CONTRACTS.listSlashCommands.responseSchema,
  ),
  claude_runtime_list_subagents: asHostCommandResponseSchema(
    CLAUDE_RUNTIME_COMMAND_CONTRACTS.listSubagents.responseSchema,
  ),
  claude_runtime_load_session_diff: asHostCommandResponseSchema(
    CLAUDE_RUNTIME_COMMAND_CONTRACTS.loadSessionDiff.responseSchema,
  ),
  claude_runtime_load_session_history: asHostCommandResponseSchema(
    CLAUDE_RUNTIME_COMMAND_CONTRACTS.loadSessionHistory.responseSchema,
  ),
  claude_runtime_load_session_todos: asHostCommandResponseSchema(
    CLAUDE_RUNTIME_COMMAND_CONTRACTS.loadSessionTodos.responseSchema,
  ),
  claude_runtime_search_files: asHostCommandResponseSchema(
    CLAUDE_RUNTIME_COMMAND_CONTRACTS.searchFiles.responseSchema,
  ),
  codex_app_server_request: asHostCommandResponseSchema(codexAppServerRequestResultSchema),
  dev_server_get_state: asHostCommandResponseSchema(devServerGroupStateSchema),
  dev_server_restart: asHostCommandResponseSchema(devServerGroupStateSchema),
  dev_server_start: asHostCommandResponseSchema(devServerGroupStateSchema),
  dev_server_stop: asHostCommandResponseSchema(devServerGroupStateSchema),
  filesystem_list_directory: asHostCommandResponseSchema(directoryListingSchema),
  filesystem_list_tree: asHostCommandResponseSchema(workspaceFileTreeSchema),
  filesystem_read_text_file: asHostCommandResponseSchema(workspaceTextFileReadResultSchema),
  filesystem_write_text_file: asHostCommandResponseSchema(workspaceTextFileWriteResultSchema),
  git_abort_conflict: asHostCommandResponseSchema(gitConflictAbortResultSchema),
  git_canonicalize_path: asHostCommandResponseSchema(hostCommandNonEmptyStringResponseSchema),
  git_commit_all: asHostCommandResponseSchema(gitCommitAllResultSchema),
  git_commits_ahead_behind: asHostCommandResponseSchema(commitsAheadBehindSchema),
  git_create_worktree: asHostCommandResponseSchema(gitWorktreeSummarySchema),
  git_fetch_remote: asHostCommandResponseSchema(gitFetchRemoteResultSchema),
  git_get_branches: asHostCommandResponseSchema(z.array(gitBranchSchema)),
  git_get_current_branch: asHostCommandResponseSchema(gitCurrentBranchSchema),
  git_get_diff: asHostCommandResponseSchema(z.array(fileDiffSchema)),
  git_get_status: asHostCommandResponseSchema(z.array(fileStatusSchema)),
  git_get_worktree_status: asHostCommandResponseSchema(gitWorktreeStatusSchema),
  git_get_worktree_status_summary: asHostCommandResponseSchema(gitWorktreeStatusSummarySchema),
  git_pull_branch: asHostCommandResponseSchema(gitPullBranchResultSchema),
  git_push_branch: asHostCommandResponseSchema(gitPushBranchResultSchema),
  git_rebase_abort: asHostCommandResponseSchema(gitRebaseAbortResultSchema),
  git_rebase_branch: asHostCommandResponseSchema(gitRebaseBranchResultSchema),
  git_remove_worktree: asHostCommandResponseSchema(hostCommandAcknowledgementResponseSchema),
  git_reset_worktree_selection: asHostCommandResponseSchema(gitResetWorktreeSelectionResultSchema),
  git_switch_branch: asHostCommandResponseSchema(gitCurrentBranchSchema),
  human_approve: asHostCommandResponseSchema(taskCardSchema),
  human_request_changes: asHostCommandResponseSchema(taskCardSchema),
  open_external_url: asHostCommandResponseSchema(hostCommandAcknowledgementResponseSchema),
  plan_get: asHostCommandResponseSchema(taskMetadataDocumentSchema),
  plan_save_document: asHostCommandResponseSchema(taskMetadataDocumentSchema),
  pull_request_review_context_get: asHostCommandResponseSchema(pullRequestReviewContextSchema),
  qa_approved: asHostCommandResponseSchema(taskCardSchema),
  qa_get_report: asHostCommandResponseSchema(taskMetadataDocumentSchema),
  qa_rejected: asHostCommandResponseSchema(taskCardSchema),
  repo_pull_request_sync: asHostCommandResponseSchema(hostCommandAcknowledgementResponseSchema),
  repo_runtime_health: asHostCommandResponseSchema(repoRuntimeHealthCheckSchema),
  repo_runtime_health_status: asHostCommandResponseSchema(repoRuntimeHealthCheckSchema),
  runtime_check: asHostCommandResponseSchema(runtimeCheckSchema),
  runtime_definitions_list: asHostCommandResponseSchema(z.array(runtimeDescriptorSchema)),
  runtime_ensure: asHostCommandResponseSchema(runtimeInstanceSummarySchema),
  runtime_executables_check: asHostCommandResponseSchema(runtimeExecutableCheckSchema),
  runtime_list: asHostCommandResponseSchema(z.array(runtimeInstanceSummarySchema)),
  runtime_require: asHostCommandResponseSchema(runtimeInstanceSummarySchema),
  runtime_stop: asHostCommandResponseSchema(hostCommandAcknowledgementResponseSchema),
  set_plan: asHostCommandResponseSchema(taskMetadataDocumentSchema),
  set_spec: asHostCommandResponseSchema(taskMetadataDocumentSchema),
  set_theme: asHostCommandResponseSchema(hostCommandEmptyResponseSchema),
  spec_get: asHostCommandResponseSchema(taskMetadataDocumentSchema),
  spec_save_document: asHostCommandResponseSchema(taskMetadataDocumentSchema),
  system_check: asHostCommandResponseSchema(systemCheckSchema),
  system_get_platform: asHostCommandResponseSchema(appPlatformSchema),
  system_list_open_in_tools: asHostCommandResponseSchema(z.array(systemOpenInToolInfoSchema)),
  system_open_directory_in_tool: asHostCommandResponseSchema(
    hostCommandAcknowledgementResponseSchema,
  ),
  task_approval_context_get: asHostCommandResponseSchema(taskApprovalContextLoadResultSchema),
  task_asset_discard_staged: asHostCommandResponseSchema(hostCommandEmptyResponseSchema),
  task_asset_stage: asHostCommandResponseSchema(taskAssetStageResultSchema),
  task_close: asHostCommandResponseSchema(taskCardSchema),
  task_create: asHostCommandResponseSchema(taskCardSchema),
  task_delete: asHostCommandResponseSchema(hostCommandAcknowledgementResponseSchema),
  task_direct_merge: asHostCommandResponseSchema(taskDirectMergeResultSchema),
  task_direct_merge_complete: asHostCommandResponseSchema(taskCardSchema),
  task_metadata_get: asHostCommandResponseSchema(taskMetadataPayloadSchema),
  task_pull_request_detect: asHostCommandResponseSchema(taskPullRequestDetectResultSchema),
  task_pull_request_link_merged: asHostCommandResponseSchema(taskCardSchema),
  task_pull_request_unlink: asHostCommandResponseSchema(hostCommandAcknowledgementResponseSchema),
  task_pull_request_upsert: asHostCommandResponseSchema(pullRequestSchema),
  task_reset: asHostCommandResponseSchema(taskCardSchema),
  task_reset_implementation: asHostCommandResponseSchema(taskCardSchema),
  task_session_bootstrap_abort: asHostCommandResponseSchema(hostCommandBooleanResponseSchema),
  task_session_bootstrap_complete: asHostCommandResponseSchema(hostCommandBooleanResponseSchema),
  task_session_bootstrap_prepare: asHostCommandResponseSchema(taskSessionBootstrapSchema),
  task_session_startup_lease_abort: asHostCommandResponseSchema(hostCommandBooleanResponseSchema),
  task_session_startup_lease_complete: asHostCommandResponseSchema(
    hostCommandBooleanResponseSchema,
  ),
  task_session_startup_lease_prepare: asHostCommandResponseSchema(
    hostCommandNonEmptyStringResponseSchema,
  ),
  task_store_check: asHostCommandResponseSchema(taskStoreCheckSchema),
  task_transition: asHostCommandResponseSchema(taskCardSchema),
  task_update: asHostCommandResponseSchema(taskCardSchema),
  task_worktree_get: asHostCommandResponseSchema(taskWorktreeSummarySchema.nullable()),
  tasks_list: asHostCommandResponseSchema(z.array(taskCardSchema)),
  terminal_close: asHostCommandResponseSchema(terminalCloseResponseSchema),
  terminal_create: asHostCommandResponseSchema(terminalCreateResponseSchema),
  terminal_list: asHostCommandResponseSchema(terminalListResponseSchema),
  terminal_prepare_path_input: asHostCommandResponseSchema(terminalPreparePathInputResponseSchema),
  workspace_add: asHostCommandResponseSchema(workspaceRecordSchema),
  workspace_detect_github_repository: asHostCommandResponseSchema(
    gitProviderRepositorySchema.nullable(),
  ),
  workspace_get_repo_config: asHostCommandResponseSchema(repoConfigSchema),
  workspace_get_settings_snapshot: asHostCommandResponseSchema(settingsSnapshotSchema),
  workspace_list: asHostCommandResponseSchema(z.array(workspaceRecordSchema)),
  workspace_reorder: asHostCommandResponseSchema(z.array(workspaceRecordSchema)),
  workspace_resolve_local_attachment_path: asHostCommandResponseSchema(
    localAttachmentPathResponseSchema,
  ),
  workspace_save_repo_settings: asHostCommandResponseSchema(workspaceRecordSchema),
  workspace_save_settings_snapshot: asHostCommandResponseSchema(z.array(workspaceRecordSchema)),
  workspace_select: asHostCommandResponseSchema(workspaceRecordSchema),
  workspace_stage_local_attachment: asHostCommandResponseSchema(localAttachmentPathResponseSchema),
  workspace_update_agent_model_favorites: asHostCommandResponseSchema(settingsSnapshotSchema),
  workspace_update_global_git_config: asHostCommandResponseSchema(hostCommandEmptyResponseSchema),
  workspace_update_repo_config: asHostCommandResponseSchema(workspaceRecordSchema),
  workspace_update_repo_hooks: asHostCommandResponseSchema(workspaceRecordSchema),
} as const satisfies Record<HostCommandName, HostCommandResponseSchema>;

const hostCommandNameSet = new Set<string>(HOST_COMMAND_NAMES);

export const isHostCommandName = (value: string): value is HostCommandName =>
  hostCommandNameSet.has(value);

export const parseHostCommandName = (value: string): HostCommandName => {
  if (isHostCommandName(value)) {
    return value;
  }

  throw new HostValidationError({
    message: `Unknown OpenDucktor host command: ${value}`,
    field: "command",
    details: { value },
  });
};

export const parseHostCommandResponse = (
  command: string,
  value: Parameters<typeof jsonValueSchema.parse>[0],
): JsonValue => {
  const hostCommand = parseHostCommandName(command);
  try {
    return jsonValueSchema.parse(HOST_COMMAND_RESPONSE_SCHEMAS[hostCommand].parse(value));
  } catch (cause) {
    throw new HostValidationError({
      message: `Host command '${hostCommand}' returned an invalid response.`,
      field: "response",
      cause,
      details: { command: hostCommand },
    });
  }
};
