import { HostValidationError } from "../../effect/host-errors";

export const HOST_COMMAND_NAMES = [
  "agent_session_control_fork",
  "agent_session_control_release",
  "agent_session_control_resume",
  "agent_session_control_send",
  "agent_session_control_start",
  "agent_session_control_stop",
  "agent_session_control_update_model",
  "agent_session_delete",
  "agent_session_live_list",
  "agent_session_live_load_context",
  "agent_session_live_read",
  "agent_session_live_refresh",
  "agent_session_live_reply_approval",
  "agent_session_live_reply_question",
  "agent_session_stop",
  "agent_session_upsert",
  "agent_sessions_list",
  "agent_sessions_list_for_tasks",
  "build_blocked",
  "build_completed",
  "build_resumed",
  "build_start",
  "codex_app_server_request",
  "dev_server_get_state",
  "dev_server_restart",
  "dev_server_start",
  "dev_server_stop",
  "filesystem_list_directory",
  "filesystem_list_tree",
  "filesystem_read_text_file",
  "git_abort_conflict",
  "git_canonicalize_path",
  "git_commit_all",
  "git_commits_ahead_behind",
  "git_create_worktree",
  "git_fetch_remote",
  "git_get_branches",
  "git_get_current_branch",
  "git_get_diff",
  "git_get_status",
  "git_get_worktree_status",
  "git_get_worktree_status_summary",
  "git_pull_branch",
  "git_push_branch",
  "git_rebase_abort",
  "git_rebase_branch",
  "git_remove_worktree",
  "git_reset_worktree_selection",
  "git_switch_branch",
  "human_approve",
  "human_request_changes",
  "open_external_url",
  "plan_get",
  "plan_save_document",
  "pull_request_review_context_get",
  "qa_approved",
  "qa_get_report",
  "qa_rejected",
  "repo_pull_request_sync",
  "repo_runtime_health",
  "repo_runtime_health_status",
  "runtime_check",
  "runtime_definitions_list",
  "runtime_ensure",
  "runtime_list",
  "runtime_require",
  "runtime_stop",
  "set_plan",
  "set_spec",
  "set_theme",
  "spec_get",
  "spec_save_document",
  "system_check",
  "system_get_platform",
  "system_list_open_in_tools",
  "system_open_directory_in_tool",
  "task_approval_context_get",
  "task_close",
  "task_create",
  "task_delete",
  "task_direct_merge",
  "task_direct_merge_complete",
  "task_metadata_get",
  "task_pull_request_detect",
  "task_pull_request_link_merged",
  "task_pull_request_unlink",
  "task_pull_request_upsert",
  "task_reset",
  "task_reset_implementation",
  "task_session_bootstrap_abort",
  "task_session_bootstrap_complete",
  "task_session_bootstrap_prepare",
  "task_session_startup_lease_abort",
  "task_session_startup_lease_complete",
  "task_session_startup_lease_prepare",
  "task_store_check",
  "task_transition",
  "task_update",
  "task_worktree_get",
  "tasks_list",
  "terminal_close",
  "terminal_create",
  "terminal_list",
  "terminal_prepare_path_input",
  "workspace_add",
  "workspace_detect_github_repository",
  "workspace_get_repo_config",
  "workspace_get_settings_snapshot",
  "workspace_list",
  "workspace_reorder",
  "workspace_resolve_local_attachment_path",
  "workspace_save_repo_settings",
  "workspace_save_settings_snapshot",
  "workspace_select",
  "workspace_stage_local_attachment",
  "workspace_update_global_git_config",
  "workspace_update_repo_config",
  "workspace_update_repo_hooks",
] as const;

export type HostCommandName = (typeof HOST_COMMAND_NAMES)[number];

const hostCommandNameSet = new Set<string>(HOST_COMMAND_NAMES);

export const isHostCommandName = (value: string): value is HostCommandName =>
  hostCommandNameSet.has(value);

export const parseHostCommandName = (value: string): HostCommandName => {
  if (isHostCommandName(value)) {
    return value;
  }

  throw new HostValidationError({
    message: `Unknown OpenDucktor host command: ${value}`,
    field: "command",
    details: { value },
  });
};
